default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 55432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "sillage") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "sillage") %>
  pool: <%= ENV.fetch("DB_POOL", 10) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "sillage_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "sillage_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "sillage_production") %>
