# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "exs1_contract", to: "lib/exs1_contract.js"
pin "fdr_partial_file", to: "lib/fdr_partial_file.js"
pin "fdr_sync_protocol", to: "lib/fdr_sync_protocol.js"
pin "fdr_wifi_provisioning", to: "lib/fdr_wifi_provisioning.js"
pin "flight_geometry", to: "lib/flight_geometry.js"
pin "pressure_altitude", to: "lib/pressure_altitude.js"
pin "signal_layout", to: "lib/signal_layout.js"
pin "aircraft_connection", to: "lib/aircraft_connection.js"
pin_all_from "app/javascript/controllers", under: "controllers"
