# frozen_string_literal: true

require "minitest/autorun"
require "stringio"
require "tmpdir"
require "uri"

require_relative "../migrator"

class MigratorTest < Minitest::Test
  ADMIN_URL = ENV.fetch(
    "MIGRATION_TEST_ADMIN_URL",
    "postgresql://sillage:sillage@127.0.0.1:55432/postgres"
  )

  def setup
    @database_name = "sillage_migration_test_#{Process.pid}_#{rand(1_000_000)}"
    @admin = PG.connect(ADMIN_URL)
    @admin.exec("CREATE DATABASE #{@admin.quote_ident(@database_name)}")
    uri = URI(ADMIN_URL)
    uri.path = "/#{@database_name}"
    @target_url = uri.to_s
    @target = PG.connect(@target_url)
    create_target_schema
  end

  def teardown
    @target&.close
    @admin&.exec_params(
      "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid != pg_backend_pid()",
      [ @database_name ]
    )
    @admin&.exec("DROP DATABASE IF EXISTS #{@admin.quote_ident(@database_name)}")
    @admin&.close
  end

  def test_copies_and_verifies_rows_then_resets_sequences
    Dir.mktmpdir do |directory|
      source_path = File.join(directory, "source.sqlite3")
      manifest_path = File.join(directory, "manifest.json")
      create_source_database(source_path)

      manifest = SqliteToPostgresql::Migrator.new(
        source_path:,
        target_url: @target_url,
        manifest_path:,
        confirmation: SqliteToPostgresql::CONFIRMATION,
        tables: %w[parents children],
        output: StringIO.new
      ).run!

      assert_equal true, manifest.fetch(:verified)
      assert_equal 2, manifest.dig(:tables, "parents", "count")
      assert_equal 1, manifest.dig(:tables, "children", "count")
      assert_equal "second", @target.exec("SELECT name FROM parents WHERE id = 2").getvalue(0, 0)
      assert_equal "t", @target.exec("SELECT enabled FROM parents WHERE id = 1").getvalue(0, 0)
      assert_equal({ "source" => "sqlite" }, JSON.parse(@target.exec("SELECT metadata::text FROM parents WHERE id = 1").getvalue(0, 0)))
      assert_equal "00ff", @target.exec("SELECT encode(payload, 'hex') FROM parents WHERE id = 1").getvalue(0, 0)
      assert_equal "3", @target.exec("SELECT nextval(pg_get_serial_sequence('parents', 'id'))").getvalue(0, 0)
      assert File.exist?(manifest_path)
    end
  end

  def test_refuses_a_nonempty_target
    @target.exec("INSERT INTO parents (name, enabled, metadata, payload) VALUES ('existing', true, '{}', '\\x00')")

    Dir.mktmpdir do |directory|
      source_path = File.join(directory, "source.sqlite3")
      create_source_database(source_path)

      error = assert_raises(SqliteToPostgresql::SafetyError) do
        SqliteToPostgresql::Migrator.new(
          source_path:,
          target_url: @target_url,
          manifest_path: File.join(directory, "manifest.json"),
          confirmation: SqliteToPostgresql::CONFIRMATION,
          tables: %w[parents children],
          output: StringIO.new
        ).run!
      end

      assert_includes error.message, "target must be empty"
    end
  end

  def test_requires_explicit_confirmation
    error = assert_raises(SqliteToPostgresql::SafetyError) do
      SqliteToPostgresql::Migrator.new(
        source_path: __FILE__,
        target_url: @target_url,
        manifest_path: "/tmp/unused-manifest.json",
        confirmation: "no",
        tables: %w[parents],
        output: StringIO.new
      ).run!
    end

    assert_includes error.message, "MIGRATION_CONFIRM"
  end

  def test_requires_a_consolidated_sqlite_source_without_sidecars
    Dir.mktmpdir do |directory|
      source_path = File.join(directory, "source.sqlite3")
      File.write(source_path, "sqlite")
      File.write("#{source_path}-wal", "pending")

      error = assert_raises(SqliteToPostgresql::SafetyError) do
        SqliteToPostgresql::Migrator.new(
          source_path:,
          target_url: @target_url,
          manifest_path: File.join(directory, "manifest.json"),
          confirmation: SqliteToPostgresql::CONFIRMATION,
          tables: %w[parents],
          output: StringIO.new
        ).run!
      end

      assert_includes error.message, "consolidated backup"
    end
  end

  private

  def create_target_schema
    @target.exec <<~SQL
      CREATE TABLE parents (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        payload bytea NOT NULL,
        metadata json NOT NULL,
        enabled boolean NOT NULL,
        name text NOT NULL
      );
      CREATE TABLE children (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parent_id bigint NOT NULL REFERENCES parents(id),
        note text
      );
    SQL
  end

  def create_source_database(path)
    source = SQLite3::Database.new(path)
    source.execute_batch <<~SQL
      PRAGMA foreign_keys = ON;
      CREATE TABLE parents (
        id integer PRIMARY KEY AUTOINCREMENT,
        name text NOT NULL,
        enabled boolean NOT NULL,
        metadata json NOT NULL,
        payload blob NOT NULL
      );
      CREATE TABLE children (
        id integer PRIMARY KEY AUTOINCREMENT,
        parent_id integer NOT NULL REFERENCES parents(id),
        note text
      );
    SQL
    source.execute(
      "INSERT INTO parents (id, name, enabled, metadata, payload) VALUES (?, ?, ?, ?, ?)",
      [ 1, "first", 1, JSON.generate(source: "sqlite"), SQLite3::Blob.new("\x00\xff") ]
    )
    source.execute(
      "INSERT INTO parents (id, name, enabled, metadata, payload) VALUES (?, ?, ?, ?, ?)",
      [ 2, "second", 0, JSON.generate(source: "sqlite"), SQLite3::Blob.new("bytes") ]
    )
    source.execute("INSERT INTO children (id, parent_id, note) VALUES (1, 2, NULL)")
  ensure
    source&.close
  end
end
