// Generated from protocol/exs1.json. Do not edit.
export const USB_PROTOCOL_VERSION = 1
export const USB_CHUNK_SIZE = 4096
export const MAX_REQUEST_PAYLOAD = 192
export const FRAME_MAGIC = Uint8Array.from([69, 88, 83, 49])
export const FRAME_HEADER_SIZE = 20
export const UsbMessage = Object.freeze({
  HELLO: 1,
  DEVICE_INFO: 2,
  NEXT_FILE: 3,
  FILE_MANIFEST: 4,
  NO_FILE: 5,
  READ_CHUNK: 6,
  FILE_CHUNK: 7,
  ACK_FILE: 8,
  ACK_ACCEPTED: 9,
  STORAGE_STATUS: 10,
  STORAGE_STATUS_DATA: 11,
  STATUS: 12,
  STATUS_DATA: 13,
  DIAGNOSTICS: 14,
  DIAGNOSTICS_DATA: 15,
  CONFIG: 16,
  CONFIG_DATA: 17,
  SET_CONFIG: 18,
  DEBUG: 19,
  DEBUG_DATA: 20,
  WIFI: 21,
  WIFI_DATA: 22,
  SECURITY: 23,
  SECURITY_DATA: 24,
  MEMORY: 25,
  MEMORY_DATA: 26,
  RATE_STATUS: 27,
  RATE_STATUS_DATA: 28,
  STORAGE_PERFORMANCE: 29,
  STORAGE_PERFORMANCE_DATA: 30,
  ERASE_RECORDINGS: 31,
  ERASE_RECORDINGS_DATA: 32,
  RECORDING: 33,
  RECORDING_DATA: 34,
  SET_RECORDING: 35,
  ERROR: 255
})
export const UsbCapability = Object.freeze({
  FILE_SYNC: 1,
  STATUS: 2,
  CONFIG: 4,
  DIAGNOSTICS: 8,
  DEBUG: 16,
  WIFI: 32,
  SECURITY: 64,
  MEMORY: 128,
  RATE_STATUS: 256,
  STORAGE_PERFORMANCE: 512,
  ERASE_RECORDINGS: 1024,
  RECORDING_CONTROL: 2048
})
export const EraseRecordingsResult = Object.freeze({
  OK: 0,
  STORAGE_ERROR: 1
})
export const RecordingControlResult = Object.freeze({
  OK: 0,
  STORAGE_ERROR: 1,
  INVALID_DATA: 2,
  UNAUTHORIZED: 3
})
export const UsbErrorCode = Object.freeze({
  BAD_FRAME: 1,
  BAD_SEQUENCE: 2,
  NOT_READY: 3,
  BAD_REQUEST: 4,
  STORAGE_ERROR: 5,
  HASH_MISMATCH: 6,
  AUTHENTICATION_REQUIRED: 7
})
export const Exs1Layout = Object.freeze({
  FRAME_HEADER: 20,
  DEVICE_INFO: 64,
  FILE_MANIFEST: 72,
  READ_CHUNK: 16,
  FILE_CHUNK_PREFIX: 16,
  ACK_FILE: 36,
  ERROR: 8,
  STORAGE_STATUS: 20,
  STATUS: 20,
  DIAGNOSTICS: 20,
  CONFIG: 8,
  BLE_DEVICE_INFO: 64,
  SECURITY_STATUS: 20,
  MEMORY_STATUS: 82,
  RATE_STATUS: 20,
  STORAGE_PERFORMANCE: 76,
  ERASE_RECORDINGS_RESULT: 16,
  RECORDING_CONTROL: 4
})
export const EXS1_GOLDEN_FRAME_HEX = "455853310101000040302010040000001386b98b00010203"
